# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Scan the webapplication

concurrency: 
  group: ${{ github.repository }}

on:
  workflow_run:
    workflows: ["packtracker.io"]
    branches: [master]
    types: 
      - completed

jobs:
  zap_scan:
  
    runs-on: ubuntu-latest
  
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://helpmap.io'
